### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by Stanislav-Lapata** [estin/simple-completion-language-server#1]
What do you think about adding snippets?
if I open `.rb` file, i get snippets for ruby files
```irb -> binding.irb```
If I open `.js` or `.ts` i get snippets for JS files
```clo -> console.log('$1:', $1)```

**Comment by estin** [comment]
I think snippets may be implemented.
I will try do it soon.

**Comment by estin** [comment]
Hi!
You can try first implementation of snippets (+completion fixes)

**Comment by Stanislav-Lapata** [comment]
It looks good, Thanks!!

**Comment by estin** [comment]
Now snippets must be located in `~/.config/helix/snippets` or declared via `SNIPPETS_PATH` env
